root: true

env:
  es6: true
  mocha: true
  node: true

rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 4, { SwitchCase: 1 }]
  no-trailing-spaces: error
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]
